### ISSUE TITLE
SonarCloud check improvement

### ISSUE THREAD

**Issue by yurake** [yurake/k8s-3tier-webapp#2752]
### Description
* fix the analysis has warnings
Shallow clone detected during the analysis. Some files will miss SCM information. This will affect features like auto-assignment of issues. Please configure your build to disable shallow clone.

```yml
- uses: actions/checkout@v3
  with:
    fetch-depth: 0
```

* use sonarcloud cache
github-action saple below
```yml
name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=yurake_jaxrs-hazelcast-quarkus
```

### Related links
* https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
* https://sonarcloud.io/project/configuration?id=yurake_jaxrs-hazelcast-quarkus&analysisMode=GitHubActions
