### ISSUE TITLE
Migrate minikube official github actions 

### ISSUE THREAD

**Issue by yurake** [yurake/k8s-3tier-webapp#2830]
### Description

Expected
```yaml
    steps:
    - name: start minikube
      id: minikube
      uses: medyagh/setup-minikube@master
```

Actual
```yaml
      - name: setup minikube
        uses: opsgang/ga-setup-minikube@v0.1.2
```

### Related links
* https://minikube.sigs.k8s.io/docs/tutorials/setup_minikube_in_github_actions/
